import { shallow, mount } from 'enzyme';
import React from 'react';
import PeopleDisplay from './PeopleDisplay'

describe('PeopleDisplay component', function () {

  const peopleData = [
    {
      "name": "Luke Skywalker",
      "height": "172",
      "mass": "77",
      "hair_color": "blond",
      "skin_color": "fair",
      "eye_color": "blue",
      "birth_year": "19BBY",
      "gender": "male",
      "homeworld": {
        "name": "Tatooine",
        "rotation_period": "23",
        "orbital_period": "304",
        "diameter": "10465",
        "climate": "arid",
        "gravity": "1 standard",
        "terrain": "desert",
        "surface_water": "1",
        "population": "200000",
        "residents": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/62/"
        ],
        "films": [
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-09T13:50:49.641000Z",
        "edited": "2014-12-21T20:48:04.175778Z",
        "url": "http://swapi.co/api/planets/1/"
      },
      "films": [
        "http://swapi.co/api/films/2/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/3/",
        "http://swapi.co/api/films/1/",
        "http://swapi.co/api/films/7/"
      ],
      "species": {
        "name": "Human",
        "classification": "mammal",
        "designation": "sentient",
        "average_height": "180",
        "skin_colors": "caucasian, black, asian, hispanic",
        "hair_colors": "blonde, brown, black, red",
        "eye_colors": "brown, blue, green, hazel, grey, amber",
        "average_lifespan": "120",
        "homeworld": "http://swapi.co/api/planets/9/",
        "language": "Galactic Basic",
        "people": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/5/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/10/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/12/",
          "http://swapi.co/api/people/14/",
          "http://swapi.co/api/people/18/",
          "http://swapi.co/api/people/19/",
          "http://swapi.co/api/people/21/",
          "http://swapi.co/api/people/22/",
          "http://swapi.co/api/people/25/",
          "http://swapi.co/api/people/26/",
          "http://swapi.co/api/people/28/",
          "http://swapi.co/api/people/29/",
          "http://swapi.co/api/people/32/",
          "http://swapi.co/api/people/34/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/51/",
          "http://swapi.co/api/people/60/",
          "http://swapi.co/api/people/61/",
          "http://swapi.co/api/people/62/",
          "http://swapi.co/api/people/66/",
          "http://swapi.co/api/people/67/",
          "http://swapi.co/api/people/68/",
          "http://swapi.co/api/people/69/",
          "http://swapi.co/api/people/74/",
          "http://swapi.co/api/people/81/",
          "http://swapi.co/api/people/84/",
          "http://swapi.co/api/people/85/",
          "http://swapi.co/api/people/86/",
          "http://swapi.co/api/people/35/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T13:52:11.567000Z",
        "edited": "2015-04-17T06:59:55.850671Z",
        "url": "http://swapi.co/api/species/1/"
      },
      "vehicles": [
        "http://swapi.co/api/vehicles/14/",
        "http://swapi.co/api/vehicles/30/"
      ],
      "starships": [
        "http://swapi.co/api/starships/12/",
        "http://swapi.co/api/starships/22/"
      ],
      "created": "2014-12-09T13:50:51.644000Z",
      "edited": "2014-12-20T21:17:56.891000Z",
      "url": "http://swapi.co/api/people/1/",
      "id": "34a4e618-5b99-4087-a4ff-16cecb9d8168",
      "favorite": false
    },
    {
      "name": "C-3PO",
      "height": "167",
      "mass": "75",
      "hair_color": "n/a",
      "skin_color": "gold",
      "eye_color": "yellow",
      "birth_year": "112BBY",
      "gender": "n/a",
      "homeworld": {
        "name": "Tatooine",
        "rotation_period": "23",
        "orbital_period": "304",
        "diameter": "10465",
        "climate": "arid",
        "gravity": "1 standard",
        "terrain": "desert",
        "surface_water": "1",
        "population": "200000",
        "residents": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/62/"
        ],
        "films": [
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-09T13:50:49.641000Z",
        "edited": "2014-12-21T20:48:04.175778Z",
        "url": "http://swapi.co/api/planets/1/"
      },
      "films": [
        "http://swapi.co/api/films/2/",
        "http://swapi.co/api/films/5/",
        "http://swapi.co/api/films/4/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/3/",
        "http://swapi.co/api/films/1/"
      ],
      "species": {
        "name": "Droid",
        "classification": "artificial",
        "designation": "sentient",
        "average_height": "n/a",
        "skin_colors": "n/a",
        "hair_colors": "n/a",
        "eye_colors": "n/a",
        "average_lifespan": "indefinite",
        "homeworld": null,
        "language": "n/a",
        "people": [
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/3/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/23/",
          "http://swapi.co/api/people/87/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T15:16:16.259000Z",
        "edited": "2015-04-17T06:59:43.869528Z",
        "url": "http://swapi.co/api/species/2/"
      },
      "vehicles": [],
      "starships": [],
      "created": "2014-12-10T15:10:51.357000Z",
      "edited": "2014-12-20T21:17:50.309000Z",
      "url": "http://swapi.co/api/people/2/",
      "id": "3a9c9097-350a-48aa-81a8-445b4f058b11",
      "favorite": false
    },
    {
      "name": "R2-D2",
      "height": "96",
      "mass": "32",
      "hair_color": "n/a",
      "skin_color": "white, blue",
      "eye_color": "red",
      "birth_year": "33BBY",
      "gender": "n/a",
      "homeworld": {
        "name": "Naboo",
        "rotation_period": "26",
        "orbital_period": "312",
        "diameter": "12120",
        "climate": "temperate",
        "gravity": "1 standard",
        "terrain": "grassy hills, swamps, forests, mountains",
        "surface_water": "12",
        "population": "4500000000",
        "residents": [
          "http://swapi.co/api/people/3/",
          "http://swapi.co/api/people/21/",
          "http://swapi.co/api/people/36/",
          "http://swapi.co/api/people/37/",
          "http://swapi.co/api/people/38/",
          "http://swapi.co/api/people/39/",
          "http://swapi.co/api/people/42/",
          "http://swapi.co/api/people/60/",
          "http://swapi.co/api/people/61/",
          "http://swapi.co/api/people/66/",
          "http://swapi.co/api/people/35/"
        ],
        "films": [
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/"
        ],
        "created": "2014-12-10T11:52:31.066000Z",
        "edited": "2014-12-20T20:58:18.430000Z",
        "url": "http://swapi.co/api/planets/8/"
      },
      "films": [
        "http://swapi.co/api/films/2/",
        "http://swapi.co/api/films/5/",
        "http://swapi.co/api/films/4/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/3/",
        "http://swapi.co/api/films/1/",
        "http://swapi.co/api/films/7/"
      ],
      "species": {
        "name": "Droid",
        "classification": "artificial",
        "designation": "sentient",
        "average_height": "n/a",
        "skin_colors": "n/a",
        "hair_colors": "n/a",
        "eye_colors": "n/a",
        "average_lifespan": "indefinite",
        "homeworld": null,
        "language": "n/a",
        "people": [
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/3/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/23/",
          "http://swapi.co/api/people/87/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T15:16:16.259000Z",
        "edited": "2015-04-17T06:59:43.869528Z",
        "url": "http://swapi.co/api/species/2/"
      },
      "vehicles": [],
      "starships": [],
      "created": "2014-12-10T15:11:50.376000Z",
      "edited": "2014-12-20T21:17:50.311000Z",
      "url": "http://swapi.co/api/people/3/",
      "id": "998bf554-6ea9-402f-92bd-15df5b5d4408",
      "favorite": false
    },
    {
      "name": "Darth Vader",
      "height": "202",
      "mass": "136",
      "hair_color": "none",
      "skin_color": "white",
      "eye_color": "yellow",
      "birth_year": "41.9BBY",
      "gender": "male",
      "homeworld": {
        "name": "Tatooine",
        "rotation_period": "23",
        "orbital_period": "304",
        "diameter": "10465",
        "climate": "arid",
        "gravity": "1 standard",
        "terrain": "desert",
        "surface_water": "1",
        "population": "200000",
        "residents": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/62/"
        ],
        "films": [
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-09T13:50:49.641000Z",
        "edited": "2014-12-21T20:48:04.175778Z",
        "url": "http://swapi.co/api/planets/1/"
      },
      "films": [
        "http://swapi.co/api/films/2/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/3/",
        "http://swapi.co/api/films/1/"
      ],
      "species": {
        "name": "Human",
        "classification": "mammal",
        "designation": "sentient",
        "average_height": "180",
        "skin_colors": "caucasian, black, asian, hispanic",
        "hair_colors": "blonde, brown, black, red",
        "eye_colors": "brown, blue, green, hazel, grey, amber",
        "average_lifespan": "120",
        "homeworld": "http://swapi.co/api/planets/9/",
        "language": "Galactic Basic",
        "people": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/5/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/10/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/12/",
          "http://swapi.co/api/people/14/",
          "http://swapi.co/api/people/18/",
          "http://swapi.co/api/people/19/",
          "http://swapi.co/api/people/21/",
          "http://swapi.co/api/people/22/",
          "http://swapi.co/api/people/25/",
          "http://swapi.co/api/people/26/",
          "http://swapi.co/api/people/28/",
          "http://swapi.co/api/people/29/",
          "http://swapi.co/api/people/32/",
          "http://swapi.co/api/people/34/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/51/",
          "http://swapi.co/api/people/60/",
          "http://swapi.co/api/people/61/",
          "http://swapi.co/api/people/62/",
          "http://swapi.co/api/people/66/",
          "http://swapi.co/api/people/67/",
          "http://swapi.co/api/people/68/",
          "http://swapi.co/api/people/69/",
          "http://swapi.co/api/people/74/",
          "http://swapi.co/api/people/81/",
          "http://swapi.co/api/people/84/",
          "http://swapi.co/api/people/85/",
          "http://swapi.co/api/people/86/",
          "http://swapi.co/api/people/35/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T13:52:11.567000Z",
        "edited": "2015-04-17T06:59:55.850671Z",
        "url": "http://swapi.co/api/species/1/"
      },
      "vehicles": [],
      "starships": [
        "http://swapi.co/api/starships/13/"
      ],
      "created": "2014-12-10T15:18:20.704000Z",
      "edited": "2014-12-20T21:17:50.313000Z",
      "url": "http://swapi.co/api/people/4/",
      "id": "956110d2-60a4-473c-bb38-09fa9a175fa2",
      "favorite": false
    },
    {
      "name": "Leia Organa",
      "height": "150",
      "mass": "49",
      "hair_color": "brown",
      "skin_color": "light",
      "eye_color": "brown",
      "birth_year": "19BBY",
      "gender": "female",
      "homeworld": {
        "name": "Alderaan",
        "rotation_period": "24",
        "orbital_period": "364",
        "diameter": "12500",
        "climate": "temperate",
        "gravity": "1 standard",
        "terrain": "grasslands, mountains",
        "surface_water": "40",
        "population": "2000000000",
        "residents": [
          "http://swapi.co/api/people/5/",
          "http://swapi.co/api/people/68/",
          "http://swapi.co/api/people/81/"
        ],
        "films": [
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T11:35:48.479000Z",
        "edited": "2014-12-20T20:58:18.420000Z",
        "url": "http://swapi.co/api/planets/2/"
      },
      "films": [
        "http://swapi.co/api/films/2/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/3/",
        "http://swapi.co/api/films/1/",
        "http://swapi.co/api/films/7/"
      ],
      "species": {
        "name": "Human",
        "classification": "mammal",
        "designation": "sentient",
        "average_height": "180",
        "skin_colors": "caucasian, black, asian, hispanic",
        "hair_colors": "blonde, brown, black, red",
        "eye_colors": "brown, blue, green, hazel, grey, amber",
        "average_lifespan": "120",
        "homeworld": "http://swapi.co/api/planets/9/",
        "language": "Galactic Basic",
        "people": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/5/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/10/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/12/",
          "http://swapi.co/api/people/14/",
          "http://swapi.co/api/people/18/",
          "http://swapi.co/api/people/19/",
          "http://swapi.co/api/people/21/",
          "http://swapi.co/api/people/22/",
          "http://swapi.co/api/people/25/",
          "http://swapi.co/api/people/26/",
          "http://swapi.co/api/people/28/",
          "http://swapi.co/api/people/29/",
          "http://swapi.co/api/people/32/",
          "http://swapi.co/api/people/34/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/51/",
          "http://swapi.co/api/people/60/",
          "http://swapi.co/api/people/61/",
          "http://swapi.co/api/people/62/",
          "http://swapi.co/api/people/66/",
          "http://swapi.co/api/people/67/",
          "http://swapi.co/api/people/68/",
          "http://swapi.co/api/people/69/",
          "http://swapi.co/api/people/74/",
          "http://swapi.co/api/people/81/",
          "http://swapi.co/api/people/84/",
          "http://swapi.co/api/people/85/",
          "http://swapi.co/api/people/86/",
          "http://swapi.co/api/people/35/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T13:52:11.567000Z",
        "edited": "2015-04-17T06:59:55.850671Z",
        "url": "http://swapi.co/api/species/1/"
      },
      "vehicles": [
        "http://swapi.co/api/vehicles/30/"
      ],
      "starships": [],
      "created": "2014-12-10T15:20:09.791000Z",
      "edited": "2014-12-20T21:17:50.315000Z",
      "url": "http://swapi.co/api/people/5/",
      "id": "03789b48-64ac-4109-94fa-c284682af261",
      "favorite": false
    },
    {
      "name": "Owen Lars",
      "height": "178",
      "mass": "120",
      "hair_color": "brown, grey",
      "skin_color": "light",
      "eye_color": "blue",
      "birth_year": "52BBY",
      "gender": "male",
      "homeworld": {
        "name": "Tatooine",
        "rotation_period": "23",
        "orbital_period": "304",
        "diameter": "10465",
        "climate": "arid",
        "gravity": "1 standard",
        "terrain": "desert",
        "surface_water": "1",
        "population": "200000",
        "residents": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/62/"
        ],
        "films": [
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-09T13:50:49.641000Z",
        "edited": "2014-12-21T20:48:04.175778Z",
        "url": "http://swapi.co/api/planets/1/"
      },
      "films": [
        "http://swapi.co/api/films/5/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/1/"
      ],
      "species": {
        "name": "Human",
        "classification": "mammal",
        "designation": "sentient",
        "average_height": "180",
        "skin_colors": "caucasian, black, asian, hispanic",
        "hair_colors": "blonde, brown, black, red",
        "eye_colors": "brown, blue, green, hazel, grey, amber",
        "average_lifespan": "120",
        "homeworld": "http://swapi.co/api/planets/9/",
        "language": "Galactic Basic",
        "people": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/5/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/10/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/12/",
          "http://swapi.co/api/people/14/",
          "http://swapi.co/api/people/18/",
          "http://swapi.co/api/people/19/",
          "http://swapi.co/api/people/21/",
          "http://swapi.co/api/people/22/",
          "http://swapi.co/api/people/25/",
          "http://swapi.co/api/people/26/",
          "http://swapi.co/api/people/28/",
          "http://swapi.co/api/people/29/",
          "http://swapi.co/api/people/32/",
          "http://swapi.co/api/people/34/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/51/",
          "http://swapi.co/api/people/60/",
          "http://swapi.co/api/people/61/",
          "http://swapi.co/api/people/62/",
          "http://swapi.co/api/people/66/",
          "http://swapi.co/api/people/67/",
          "http://swapi.co/api/people/68/",
          "http://swapi.co/api/people/69/",
          "http://swapi.co/api/people/74/",
          "http://swapi.co/api/people/81/",
          "http://swapi.co/api/people/84/",
          "http://swapi.co/api/people/85/",
          "http://swapi.co/api/people/86/",
          "http://swapi.co/api/people/35/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T13:52:11.567000Z",
        "edited": "2015-04-17T06:59:55.850671Z",
        "url": "http://swapi.co/api/species/1/"
      },
      "vehicles": [],
      "starships": [],
      "created": "2014-12-10T15:52:14.024000Z",
      "edited": "2014-12-20T21:17:50.317000Z",
      "url": "http://swapi.co/api/people/6/",
      "id": "33592ac9-465f-4d08-b902-4e2b39b68109",
      "favorite": false
    },
    {
      "name": "Beru Whitesun lars",
      "height": "165",
      "mass": "75",
      "hair_color": "brown",
      "skin_color": "light",
      "eye_color": "blue",
      "birth_year": "47BBY",
      "gender": "female",
      "homeworld": {
        "name": "Tatooine",
        "rotation_period": "23",
        "orbital_period": "304",
        "diameter": "10465",
        "climate": "arid",
        "gravity": "1 standard",
        "terrain": "desert",
        "surface_water": "1",
        "population": "200000",
        "residents": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/62/"
        ],
        "films": [
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-09T13:50:49.641000Z",
        "edited": "2014-12-21T20:48:04.175778Z",
        "url": "http://swapi.co/api/planets/1/"
      },
      "films": [
        "http://swapi.co/api/films/5/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/1/"
      ],
      "species": {
        "name": "Human",
        "classification": "mammal",
        "designation": "sentient",
        "average_height": "180",
        "skin_colors": "caucasian, black, asian, hispanic",
        "hair_colors": "blonde, brown, black, red",
        "eye_colors": "brown, blue, green, hazel, grey, amber",
        "average_lifespan": "120",
        "homeworld": "http://swapi.co/api/planets/9/",
        "language": "Galactic Basic",
        "people": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/5/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/10/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/12/",
          "http://swapi.co/api/people/14/",
          "http://swapi.co/api/people/18/",
          "http://swapi.co/api/people/19/",
          "http://swapi.co/api/people/21/",
          "http://swapi.co/api/people/22/",
          "http://swapi.co/api/people/25/",
          "http://swapi.co/api/people/26/",
          "http://swapi.co/api/people/28/",
          "http://swapi.co/api/people/29/",
          "http://swapi.co/api/people/32/",
          "http://swapi.co/api/people/34/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/51/",
          "http://swapi.co/api/people/60/",
          "http://swapi.co/api/people/61/",
          "http://swapi.co/api/people/62/",
          "http://swapi.co/api/people/66/",
          "http://swapi.co/api/people/67/",
          "http://swapi.co/api/people/68/",
          "http://swapi.co/api/people/69/",
          "http://swapi.co/api/people/74/",
          "http://swapi.co/api/people/81/",
          "http://swapi.co/api/people/84/",
          "http://swapi.co/api/people/85/",
          "http://swapi.co/api/people/86/",
          "http://swapi.co/api/people/35/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T13:52:11.567000Z",
        "edited": "2015-04-17T06:59:55.850671Z",
        "url": "http://swapi.co/api/species/1/"
      },
      "vehicles": [],
      "starships": [],
      "created": "2014-12-10T15:53:41.121000Z",
      "edited": "2014-12-20T21:17:50.319000Z",
      "url": "http://swapi.co/api/people/7/",
      "id": "a00f2bd1-f198-476c-8e4c-b26e2514ee72",
      "favorite": false
    },
    {
      "name": "R5-D4",
      "height": "97",
      "mass": "32",
      "hair_color": "n/a",
      "skin_color": "white, red",
      "eye_color": "red",
      "birth_year": "unknown",
      "gender": "n/a",
      "homeworld": {
        "name": "Tatooine",
        "rotation_period": "23",
        "orbital_period": "304",
        "diameter": "10465",
        "climate": "arid",
        "gravity": "1 standard",
        "terrain": "desert",
        "surface_water": "1",
        "population": "200000",
        "residents": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/62/"
        ],
        "films": [
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-09T13:50:49.641000Z",
        "edited": "2014-12-21T20:48:04.175778Z",
        "url": "http://swapi.co/api/planets/1/"
      },
      "films": [
        "http://swapi.co/api/films/1/"
      ],
      "species": {
        "name": "Droid",
        "classification": "artificial",
        "designation": "sentient",
        "average_height": "n/a",
        "skin_colors": "n/a",
        "hair_colors": "n/a",
        "eye_colors": "n/a",
        "average_lifespan": "indefinite",
        "homeworld": null,
        "language": "n/a",
        "people": [
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/3/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/23/",
          "http://swapi.co/api/people/87/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T15:16:16.259000Z",
        "edited": "2015-04-17T06:59:43.869528Z",
        "url": "http://swapi.co/api/species/2/"
      },
      "vehicles": [],
      "starships": [],
      "created": "2014-12-10T15:57:50.959000Z",
      "edited": "2014-12-20T21:17:50.321000Z",
      "url": "http://swapi.co/api/people/8/",
      "id": "4ed97fb7-1a5b-4759-bc55-23f30a9b1022",
      "favorite": false
    },
    {
      "name": "Biggs Darklighter",
      "height": "183",
      "mass": "84",
      "hair_color": "black",
      "skin_color": "light",
      "eye_color": "brown",
      "birth_year": "24BBY",
      "gender": "male",
      "homeworld": {
        "name": "Tatooine",
        "rotation_period": "23",
        "orbital_period": "304",
        "diameter": "10465",
        "climate": "arid",
        "gravity": "1 standard",
        "terrain": "desert",
        "surface_water": "1",
        "population": "200000",
        "residents": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/2/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/8/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/62/"
        ],
        "films": [
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-09T13:50:49.641000Z",
        "edited": "2014-12-21T20:48:04.175778Z",
        "url": "http://swapi.co/api/planets/1/"
      },
      "films": [
        "http://swapi.co/api/films/1/"
      ],
      "species": {
        "name": "Human",
        "classification": "mammal",
        "designation": "sentient",
        "average_height": "180",
        "skin_colors": "caucasian, black, asian, hispanic",
        "hair_colors": "blonde, brown, black, red",
        "eye_colors": "brown, blue, green, hazel, grey, amber",
        "average_lifespan": "120",
        "homeworld": "http://swapi.co/api/planets/9/",
        "language": "Galactic Basic",
        "people": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/5/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/10/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/12/",
          "http://swapi.co/api/people/14/",
          "http://swapi.co/api/people/18/",
          "http://swapi.co/api/people/19/",
          "http://swapi.co/api/people/21/",
          "http://swapi.co/api/people/22/",
          "http://swapi.co/api/people/25/",
          "http://swapi.co/api/people/26/",
          "http://swapi.co/api/people/28/",
          "http://swapi.co/api/people/29/",
          "http://swapi.co/api/people/32/",
          "http://swapi.co/api/people/34/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/51/",
          "http://swapi.co/api/people/60/",
          "http://swapi.co/api/people/61/",
          "http://swapi.co/api/people/62/",
          "http://swapi.co/api/people/66/",
          "http://swapi.co/api/people/67/",
          "http://swapi.co/api/people/68/",
          "http://swapi.co/api/people/69/",
          "http://swapi.co/api/people/74/",
          "http://swapi.co/api/people/81/",
          "http://swapi.co/api/people/84/",
          "http://swapi.co/api/people/85/",
          "http://swapi.co/api/people/86/",
          "http://swapi.co/api/people/35/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T13:52:11.567000Z",
        "edited": "2015-04-17T06:59:55.850671Z",
        "url": "http://swapi.co/api/species/1/"
      },
      "vehicles": [],
      "starships": [
        "http://swapi.co/api/starships/12/"
      ],
      "created": "2014-12-10T15:59:50.509000Z",
      "edited": "2014-12-20T21:17:50.323000Z",
      "url": "http://swapi.co/api/people/9/",
      "id": "5a95a187-8c43-4a21-80b5-3b258d6a132e",
      "favorite": false
    },
    {
      "name": "Obi-Wan Kenobi",
      "height": "182",
      "mass": "77",
      "hair_color": "auburn, white",
      "skin_color": "fair",
      "eye_color": "blue-gray",
      "birth_year": "57BBY",
      "gender": "male",
      "homeworld": {
        "name": "Stewjon",
        "rotation_period": "unknown",
        "orbital_period": "unknown",
        "diameter": "0",
        "climate": "temperate",
        "gravity": "1 standard",
        "terrain": "grass",
        "surface_water": "unknown",
        "population": "unknown",
        "residents": [
          "http://swapi.co/api/people/10/"
        ],
        "films": [],
        "created": "2014-12-10T16:16:26.566000Z",
        "edited": "2014-12-20T20:58:18.452000Z",
        "url": "http://swapi.co/api/planets/20/"
      },
      "films": [
        "http://swapi.co/api/films/2/",
        "http://swapi.co/api/films/5/",
        "http://swapi.co/api/films/4/",
        "http://swapi.co/api/films/6/",
        "http://swapi.co/api/films/3/",
        "http://swapi.co/api/films/1/"
      ],
      "species": {
        "name": "Human",
        "classification": "mammal",
        "designation": "sentient",
        "average_height": "180",
        "skin_colors": "caucasian, black, asian, hispanic",
        "hair_colors": "blonde, brown, black, red",
        "eye_colors": "brown, blue, green, hazel, grey, amber",
        "average_lifespan": "120",
        "homeworld": "http://swapi.co/api/planets/9/",
        "language": "Galactic Basic",
        "people": [
          "http://swapi.co/api/people/1/",
          "http://swapi.co/api/people/4/",
          "http://swapi.co/api/people/5/",
          "http://swapi.co/api/people/6/",
          "http://swapi.co/api/people/7/",
          "http://swapi.co/api/people/9/",
          "http://swapi.co/api/people/10/",
          "http://swapi.co/api/people/11/",
          "http://swapi.co/api/people/12/",
          "http://swapi.co/api/people/14/",
          "http://swapi.co/api/people/18/",
          "http://swapi.co/api/people/19/",
          "http://swapi.co/api/people/21/",
          "http://swapi.co/api/people/22/",
          "http://swapi.co/api/people/25/",
          "http://swapi.co/api/people/26/",
          "http://swapi.co/api/people/28/",
          "http://swapi.co/api/people/29/",
          "http://swapi.co/api/people/32/",
          "http://swapi.co/api/people/34/",
          "http://swapi.co/api/people/43/",
          "http://swapi.co/api/people/51/",
          "http://swapi.co/api/people/60/",
          "http://swapi.co/api/people/61/",
          "http://swapi.co/api/people/62/",
          "http://swapi.co/api/people/66/",
          "http://swapi.co/api/people/67/",
          "http://swapi.co/api/people/68/",
          "http://swapi.co/api/people/69/",
          "http://swapi.co/api/people/74/",
          "http://swapi.co/api/people/81/",
          "http://swapi.co/api/people/84/",
          "http://swapi.co/api/people/85/",
          "http://swapi.co/api/people/86/",
          "http://swapi.co/api/people/35/"
        ],
        "films": [
          "http://swapi.co/api/films/2/",
          "http://swapi.co/api/films/7/",
          "http://swapi.co/api/films/5/",
          "http://swapi.co/api/films/4/",
          "http://swapi.co/api/films/6/",
          "http://swapi.co/api/films/3/",
          "http://swapi.co/api/films/1/"
        ],
        "created": "2014-12-10T13:52:11.567000Z",
        "edited": "2015-04-17T06:59:55.850671Z",
        "url": "http://swapi.co/api/species/1/"
      },
      "vehicles": [
        "http://swapi.co/api/vehicles/38/"
      ],
      "starships": [
        "http://swapi.co/api/starships/48/",
        "http://swapi.co/api/starships/59/",
        "http://swapi.co/api/starships/64/",
        "http://swapi.co/api/starships/65/",
        "http://swapi.co/api/starships/74/"
      ],
      "created": "2014-12-10T16:16:29.192000Z",
      "edited": "2014-12-20T21:17:50.325000Z",
      "url": "http://swapi.co/api/people/10/",
      "id": "15e71e0d-ef5c-40aa-9300-24a21d389781",
      "favorite": false
    }
  ]
  const mockFn = jest.fn();
  const wrapper = shallow(<PeopleDisplay displayCards={peopleData} starItem={mockFn}/>)

  it('should render 10 people cards', () => {
    expect(wrapper.find('.people-cards').length).toEqual(10);
  });

  it('should render the persons name in the card', () => {
    const personName = wrapper.find('.person-name').first()
    expect(personName.props().children).toEqual('Luke Skywalker')
  });

  it('should render the persons weight in the card', () => {
    const personWeight = wrapper.find('.person-weight .value').first()
    expect(personWeight.props().children).toEqual('77')
  });

  it('should render the persons homeworld in the card', () => {
    const personHomeworld = wrapper.find('.person-hw .value').first()
    expect(personHomeworld.props().children).toEqual('Tatooine')
  });

  it('should render the persons homeworld population in the card', () => {
    const personHomeworldPop = wrapper.find('.person-hw-pop .value').first()
    expect(personHomeworldPop.props().children).toEqual('200000')
  });

  it('should render the persons species in the card', () => {
    const personSpecies = wrapper.find('.person-species .value').first()
    expect(personSpecies.props().children).toEqual('Human')
  });

  it('should execute a fn when the favorite button is clicked', function () {
    const favBtn = wrapper.find('.fav-btn').first()

    favBtn.simulate('click')
    expect(mockFn).toHaveBeenCalledTimes(1)
    favBtn.simulate('click')
    expect(mockFn).toHaveBeenCalledTimes(2)
  });

});
